name: main-conda-env
channels:
  - default
dependencies:
  - python=3.8
  - sphinx
  - pip=21.3.1  # Daily build job was working until Jan 29, broke on Jan 30, coincidentally when pip 22.0 was released
  - pandas
  - matplotlib
  - pip:
    - quantecon
    - jupyter-book
