title : Actuaries' Analytical Cookbook
author: YDAWG, DAPC and other contributors
logo: 'qe-logo-large.png'

# Short description about the book
description: >-
  A cookbook for actuaries for data and analytics

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://actuariesinstitute.github.io/cookbook
  path_to_book                : "cookbook"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
