title : Actuaries' Analytical Cookbook
author: YDAWG, DAPC and other contributors
logo: 'actuaries-logo.svg'

# Short description about the book
description: >-
  A cookbook for actuaries for data and analytics

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_repository_button         : true
  use_edit_page_button          : true

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/ActuariesInstitute/cookbook
  path_to_book       : "cookbook"
  branch                   : "main"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

launch_buttons:
  # binderhub is too slow, let's leave it
  # binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  colab_url: "https://colab.research.google.com"
  thebe                  : true
